IGNITE-16969 Add developer documentation to REST modules
apache/ignite-3 pull request #1028
Opened 2022-08-20 15:13 UTC by PakhomovAlexander

2022-08-23 11:24 UTC, valepakh commented on modules/rest-api/README.md
> +This module defines REST API's that might be provided by Ignite 3. Also, common
```suggestion
This module defines REST APIs that might be provided by Ignite 3. Also, common
```

2022-08-23 11:24 UTC, valepakh commented on modules/rest-api/README.md
> +needed to generate a valid [Open API spec](todo) from these interfaces.
Why there's no link to the spec?

2022-08-23 11:24 UTC, valepakh commented on modules/rest-api/README.md
> +problem definition and common problem handling are defined in this module. Here is how it is working:
```suggestion
problem definition and common problem handling are defined in this module. Here is how it works:
```

2022-08-23 11:24 UTC, valepakh commented on modules/rest-api/README.md
> +Ignite 3 implements the [problem/json](todo) in all endpoints. That's why
todo again

2022-08-23 11:24 UTC, valepakh commented on modules/rest/README.md
> +- starts the micronaut server at the configured port range
```suggestion
- aggregating all REST API definitions by `@OpenAPIInclude` annotation at compile time
- creating a micronaut context at runtime and injecting all needed beans into the context
- starting the micronaut server at the configured port range
```

2022-08-23 11:24 UTC, valepakh commented on modules/rest/README.md
> +During the build time, the [Open API spec]() is generated from all API definitions that are included in
Empty link

2022-08-23 11:24 UTC, valepakh commented on modules/rest/README.md
> +- create the instance of the RestFactory in IgniteImpl constructor and put the factory to the RestComponent's constructor
```suggestion
- create the instance of the RestFactory in the IgniteImpl constructor and put the factory to the RestComponent's constructor
```

2022-08-23 11:24 UTC, valepakh commented on modules/rest-api/README.md
> +- [`IgniteExceptionHandler`](src/main/java/org/apache/ignite/internal/rest/exception/handler/IgniteExceptionHandler.java)  handles `IgniteException` and returns a valid `problem/json`
I wonder why there's a link to the IgniteExceptionHandler file but not to the IgniteException?

2022-08-23 11:24 UTC, valepakh commented on modules/rest/README.md
> +- API definition [ClusterManagementApi](../rest-api/src/main/java/org/apache/ignite/internal/rest/api/cluster)
```suggestion
- API definition [ClusterManagementApi](../rest-api/src/main/java/org/apache/ignite/internal/rest/api/cluster/ClusterManagementApi.java)
```

2022-08-24 11:09 UTC, PakhomovAlexander commented on modules/rest-api/README.md
> +needed to generate a valid [Open API spec](todo) from these interfaces.
Oh, my fault.

2022-08-24 11:55 UTC, valepakh commented
LGTM

2022-08-25 18:55 UTC, kgusakov requested changes

2022-08-25 18:55 UTC, kgusakov commented on modules/rest-api/README.md
> +Ignite 3 implements the [problem/json](https://www.rfc-editor.org/rfc/rfc7807.html) in all endpoints. That's why
Do you mean media type `application/problem+json`? If no, could you rename this link, because `any/any` looks like media type in the current scope?

2022-08-25 18:55 UTC, kgusakov commented on modules/rest-api/README.md
> +- `IgniteException` is thrown in any Ignite component
Could you attach the link for this class also?

2022-08-25 19:03 UTC, sk0x50 commented
It would be nice to mention these new README files in the "root" README.md here https://github.com/apache/ignite-3/blob/main/modules/README.md

2022-08-26 12:35 UTC, kgusakov approved these changes

2022-08-30 06:58 UTC, closed without merging