IGNITE-14670 Update metastorage manager with: range with applied revision, invoke for multiple updates.
apache/ignite-3 pull request #113
Opened 2021-04-29 13:38 UTC by kgusakov

2021-04-29 14:42 UTC, alievmirza requested changes

2021-04-29 14:42 UTC, alievmirza commented on modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java
> +     * Entries will be filtered out by the current applied revision as an upper bound
Probably we should explain here what applied revision is.

2021-05-04 11:29 UTC, sk0x50 commented on modules/metastorage-common/src/main/java/org/apache/ignite/metastorage/common/Condition.java
> +         * Key of entry, which will be tested for condition.
It should be a one-line comment.

2021-05-04 11:29 UTC, sk0x50 commented on modules/metastorage-common/src/main/java/org/apache/ignite/metastorage/common/Condition.java
> +         * Key of entry, which will be tested for condition.
Please use one-line Javadoc for such cases.

2021-05-04 11:29 UTC, sk0x50 commented on modules/metastorage-common/src/main/java/org/apache/ignite/metastorage/common/Conditions.java
> +    public static Conditions key(Key key) {
Please add Javadoc here.

2021-05-04 11:29 UTC, sk0x50 commented on modules/metastorage/src/main/java/org/apache/ignite/internal/metastorage/MetaStorageManager.java
> +    public @NotNull CompletableFuture<Boolean> invoke(@NotNull Condition cond,
coding guideline does not allow that. please see https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guidelines#CodingGuidelines-MethodArguments

I think it should be as follows:
```
    public @NotNull CompletableFuture<Boolean> invoke(
        @NotNull Condition cond,
        @NotNull Operation success,
        @NotNull Operation failure
    ) {
```

2021-05-04 12:30 UTC, closed without merging