IGNITE-18087 Populate DistributionZoneManager with CMG listeners to logical topology events
apache/ignite-3 pull request #1436
Opened 2022-12-12 15:36 UTC by alievmirza

https://issues.apache.org/jira/browse/IGNITE-18087

2022-12-14 11:40 UTC, sergeyuttsel commented on modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java
> +                throw new RuntimeException(e);
Need to use IgniteInternalException or other.

2022-12-14 11:40 UTC, sergeyuttsel commented on modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java
> +    private static final String DISTRIBUTION_ZONES_LOGICAL_TOPOLOGY_PREFIX = "distributionZones.logicalTopology";
it isn't a prefix. It's just a DISTRIBUTION_ZONES_LOGICAL_TOPOLOGY or DISTRIBUTION_ZONES_LOGICAL_TOPOLOGY_KEY

2022-12-14 11:40 UTC, sergeyuttsel commented on modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java
> +    private static final String DISTRIBUTION_ZONES_LOGICAL_TOPOLOGY_VERSION_PREFIX = "distributionZones.logicalTopologyVersion";
Not a prefix.

2022-12-14 11:40 UTC, sergeyuttsel commented on modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZonesUtil.java
> +    private static final ByteArray DISTRIBUTION_ZONES_LOGICAL_TOPOLOGY_VERSION_KEY =
Need to move "private static final" fields on top.

2022-12-16 08:49 UTC, sanpwc commented on modules/distribution-zones/src/main/java/org/apache/ignite/internal/distributionzones/DistributionZoneManager.java
> +            updateMetaStorageKeys(newTopology, false);
Confusing naming, I'd rather use updateLogicalTopologyInMetaStorage.

2022-12-16 14:12 UTC, sanpwc requested changes

2022-12-16 16:13 UTC, sanpwc approved these changes

2022-12-19 06:30 UTC, merged