IGNITE-19666 Remove nullmaps from binary tuples in C++
apache/ignite-3 pull request #2256
Opened 2023-06-26 13:36 UTC by ademakov

2023-06-30 08:42 UTC, isapego approved these changes
Looks good overall

2023-06-30 08:42 UTC, isapego commented on modules/platforms/cpp/ignite/tuple/binary_tuple_builder.cpp
>      std::size_t tableSize = entry_size * element_count;
```suggestion
    std::size_t table_size = entry_size * element_count;
```

2023-06-30 10:33 UTC, SammyVimes requested changes

2023-06-30 11:09 UTC, ademakov commented on modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleParser.java
> +        buffer.duplicate().position(begin).limit(end).get(bytes);
This is available only since jdk13, for jdk11 it won't work.

2023-06-30 11:21 UTC, ademakov commented on modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleBuilder.java
> +            ensure(bytes.length + 1);
Out of bad habit to count every instruction. This saves one comparison.

2023-06-30 13:12 UTC, SammyVimes commented on modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleParser.java
> +        buffer.duplicate().position(begin).limit(end).get(bytes);
Oh, sorry

2023-06-30 13:13 UTC, SammyVimes commented on modules/binary-tuple/src/main/java/org/apache/ignite/internal/binarytuple/BinaryTupleBuilder.java
> +            ensure(bytes.length + 1);
Ok

2023-06-30 13:13 UTC, SammyVimes approved these changes
LGTM

2023-06-30 14:50 UTC, merged

2023-07-03 04:32 UTC, ptupitsyn commented
@SammyVimes please make sure to include extended commit message details when merging PRs:
1. Copy the PR description (if there is anything meaningful).
2. Include `Co-authored-by: NAME <NAME@EXAMPLE.COM>` when there are multiple authors - GitHub generates those lines automatically I believe.