IGNITE-14000 Fix codestyle in cli and cli-common modules
apache/ignite-3 pull request #31
Opened 2021-01-20 15:03 UTC by kgusakov

2021-01-21 08:31 UTC, sk0x50 commented on modules/cli/src/main/java/org/apache/ignite/cli/IgnitePaths.java
> +     * Work directory for Ignite server and CLI operation.
This javadoc can be a one-liner.

2021-01-21 08:31 UTC, sk0x50 commented on modules/cli/src/main/java/org/apache/ignite/cli/IgnitePaths.java
> +    /** Path where CLI module artifacts will be placed. */
One-line Javadoc comments allowed and preferred for fields. I'm not sure that this can be applied to methods.

2021-01-23 00:03 UTC, vkulichenko requested changes
`cli.common.IgniteCommand` interface doesn't have any JavaDoc. Please describe the purpose of the interface, how it should be used, etc.

`MavenArtifactResolver` has a TODO without a ticket on line 152.

+ see inline review comments

2021-01-23 00:03 UTC, vkulichenko commented on modules/cli/src/main/java/org/apache/ignite/cli/builtins/config/HttpClientFactory.java
Remove empty line.

2021-01-25 19:16 UTC, vkulichenko approved these changes

2021-01-25 19:16 UTC, merged