IGNITE-23818 Test tuple from table deserialization
apache/ignite-3 pull request #4815
Opened 2024-12-02 14:40 UTC by valepakh

https://issues.apache.org/jira/browse/IGNITE-23818

Enabled a test which tested `Tuple` retrieved from the Table API after fixing https://github.com/apache/ignite-3/pull/4833.
Added a test for `Tuple` argument job without a client.

2024-12-02 15:59 UTC, ptupitsyn requested changes

2024-12-02 15:59 UTC, ptupitsyn commented on modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java
> +        out.defaultWriteObject();
This uses Java serialization, right? Can we use `MARSHALLED_TUPLE` mode for tuples instead?

2024-12-02 16:10 UTC, ptupitsyn commented on modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java
> +        out.defaultWriteObject();
> Do you mean TupleWithSchemaMarshalling?
Yes. 
We should prefer formats that can be used by non-Java clients as well.

2024-12-02 16:25 UTC, ptupitsyn commented on modules/api/src/main/java/org/apache/ignite/table/TupleImpl.java
> +        out.defaultWriteObject();
What happens if I run the reproducer in the ticket using the client API?

2024-12-06 13:32 UTC, ptupitsyn approved these changes

2024-12-06 15:05 UTC, PakhomovAlexander approved these changes

2024-12-06 15:06 UTC, merged