IGNITE-23252 ItReplicaLifecycleTest is unstable
apache/ignite-3 pull request #4956
Opened 2024-12-23 12:14 UTC by JAkutenshi

JIRA Ticket: [IGNITE-23252](https://issues.apache.org/jira/browse/IGNITE-23252)

## The goal

## The reason

## The solution

2025-01-29 16:49 UTC, kgusakov requested changes

2025-01-29 16:49 UTC, kgusakov commented on modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/LocalPartitionReplicaEventParameters.java
> +    private final long revision;
We have a special CausalEventParameters for this case

2025-01-31 08:30 UTC, JAkutenshi commented on modules/partition-replicator/src/main/java/org/apache/ignite/internal/partition/replicator/LocalPartitionReplicaEventParameters.java
> +    private final long revision;
Done

2025-02-03 09:46 UTC, sanpwc approved these changes

2025-02-03 10:14 UTC, merged