IGNITE-17113 Added info on distributed computing
apache/ignite-3 pull request #857
Opened 2022-06-06 14:02 UTC by IgGusev

2022-06-06 17:28 UTC, ptupitsyn requested changes

2022-06-06 17:28 UTC, ptupitsyn commented on docs/_docs/compute/compute.adoc
> +NOTE: Unlike Ignite 2, jobs are currently not serialized.
There are no plans to serialize jobs for now, so let's drop "currently".

2022-06-06 17:28 UTC, ptupitsyn commented on docs/_docs/compute/compute.adoc
> +== .NET: Thin
```suggestion
== .NET
```

2022-06-06 17:28 UTC, ptupitsyn commented on docs/_docs/compute/compute.adoc
> +NOTE: Unlike Ignite 2, jobs are currently not serialized.
```suggestion

```

2022-06-06 17:28 UTC, ptupitsyn commented on docs/_docs/compute/compute.adoc
> +NOTE: Unlike Ignite 2, jobs are currently not serialized.
The API only accepts the Java job class name, so there is no possibility of job serialization. I'm not sure if this remark makes sense here.

2022-06-07 11:06 UTC, rpuch commented on docs/_docs/compute/compute.adoc
> +        .executeColocated("PUBLIC.test", Tuple.create(Map.of("k", 1)), GetNodeNameJob.class)
Should it be replaced with a call to `NodeNameJob`? If not, then `GetNodeNameJob` code is missing.

2022-06-07 11:06 UTC, rpuch commented on docs/_docs/compute/compute.adoc
> +        .executeColocated("PUBLIC.test", 1, Mapper.of(Integer.class), GetNodeNameJob.class)
Same thing about the job

2022-06-07 11:08 UTC, ptupitsyn requested changes

2022-06-07 11:11 UTC, ptupitsyn approved these changes
Looks good to me :+1:

2022-06-07 11:45 UTC, rpuch approved these changes

2022-12-06 09:13 UTC, closed without merging